### ISSUE TITLE
support babel's `optimisation.react.inlineElements`

### ISSUE THREAD

**Issue by aeosynth** [anthonyshort/deku#244]
http://babeljs.io/blog/2015/03/31/5.0.0/#inline-elements

basically, change virtual elements `attributes` to `props`

alternatively, i suppose we could ask babel to support other virtual element signatures

**Comment by anthonyshort** [comment]
Seems kind of odd that they have React optimisations like that in there. You can get the same thing by just pulling virtual elements out of the render function and reusing them. Deku will skip over nodes if they're the same as the previous node. 

It could possibly be worth changing the property name if it means free optimisations, but I'll look into it.

**Comment by aeosynth** [comment]
that's [constant elements](http://babeljs.io/blog/2015/03/31/5.0.0/#constant-elements) :D

**Comment by anthonyshort** [comment]
Derp, my bad. Yeah of course. I'm guessing we could support that with a Babel transform too.
