### ISSUE TITLE
Documentation - Basics options not in sync with content

### ISSUE THREAD

**Issue by rcpacheco** [anthonyshort/deku#380]
The left index indicates that there are 5 section in the Basics item
3.1 Migrating ..
3.2 Elements
3.3 JSX
3.4 Events
3.5 Components

If you choose the Basics Page you find the following content not in sync
Getting Started (missing from index)
(Migrating is not mentiones)
Virtual Elements (Elements)
JSX
Events
Components

**Comment by rcpacheco** [comment]
Also, If you click the the Basics section (http://dekujs.github.io/deku/docs/basics/index.html) and from there click Getting started, you get the getting-started.md page but not the html version

**Comment by anthonyshort** [comment]
Hey @rcpacheco, you can update these in the `docs/README.md` file. Feel free to open up a PR :)
