### ISSUE TITLE
what happend?

### ISSUE THREAD

**Issue by flosse** [anthonyshort/deku#424]
... is this project dead?

**Comment by rstacruz** [comment]
In the mean time, you guys can try:
http://ricostacruz.com/decca

**Comment by anthonyshort** [comment]
Hey @flosse the project isn't dead, it's just humming along right now. Everything is stable and working. However, there are a bunch of other projects in this space so if you're looking for something that's still got a lot of development going on, you should checkout [Choo](https://github.com/yoshuawuyts/choo).

**Comment by flosse** [comment]
@rstacruz thanks for the link!

@anthonyshort I'm glad to hear that the project is still alive :) And Choo looks interesting too :) thx.
